django-chat-application/app/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("room.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


django-chat-application/app/room/urls.py
from django.urls import path

from . import views


app_name = "room"

urlpatterns = [
    path("", views.home_page, name="home"),


    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('register/', views.register_user, name='register'),


    path("room/", views.rooms_page, name="rooms"),
    path("room/<int:room_id>", views.get_room, name="room"),
    path("room/create/", views.createRoom, name="create-room"),
    path("room/edit/<int:room_id>", views.update_room, name="update-room"),
    path('room/delete/<int:room_id>', views.delete_room, name="delete-room"),
    path('room/<int:room_id>/delete-message/<int:msg_id>/', views.delete_message, name='delete-message'),


    path('topics/', views.topicsPage, name='topics'),
    path('activity/', views.activityPage, name='activity'),


    path("profile/<int:user_id>/", views.userProfile, name="profile"),
    path("edit-profile/", views.editUser, name="edit-user"),
]

django-chat-application/app/room/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):

    name = models.CharField(max_length=64)
    email = models.EmailField(unique=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True, default='avatar.svg')


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name
    

class Room(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="created_rooms")
    participants = models.ManyToManyField(User, related_name="participants", blank=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True, related_name="rooms")


    class Meta:
        ordering = ['-updated_at', '-created_at']


    def __str__(self):
        return self.name



class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_messages")
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="room_messages")
    body = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']


    def __str__(self):
        return self.body[0:50]

django-chat-application/app/room/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

django-chat-application/app/room/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import MyUserCreationForm

from room.forms import UserForm

from django.shortcuts import render, redirect
from django.db.models import Q


from room.models import *


# Create your views here.


def register_user(request):

    form_template = MyUserCreationForm()

    if request.method == 'POST':

        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect("room:home")
        else:
            return render(request, 'room/login.html', {
                "message": "an error occured during registration. Please try again",
                "form": form_template,
            })

    return render(request, 'room/register.html', {
        "form": form_template,
    })


def login_page(request):

    if request.method == 'POST':

        if request.user.is_authenticated:
            return redirect("room:home")
        
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = None
        try:
            user = User.objects.get(email=email)
        except:
            return render(request, 'room/login.html', {
                "message": "Email does not exist"
            })
        else:
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect("room:home")
            return render(request, 'room/login.html', {
                "message": "Invalid login credentials"
            })

    # if there is a get request        
    return render(request, 'room/login.html')


def logout_page(request):

    if request.user.is_authenticated:
        logout(request)
    
    return redirect("room:login")


def home_page(request):

    q = request.GET.get("q") if request.GET.get("q") else ""

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )
    topics = Topic.objects.all()[0:5]
    room_messages = Message.objects.filter(
        Q(room__name__icontains=q) |
        Q(room__topic__name__icontains=q)
    )

    room_count = rooms.count()

    return render(request, 'room/home.html', {
        "rooms": rooms,
        "topics": topics,
        "room_count": room_count,
        "room_messages": room_messages,
    })



def rooms_page(request):

    # Query all the available rooms
    available_rooms = Room.objects.all()

    return render(request, "room/rooms.html", {
        "rooms": available_rooms
    })


def get_room(request, room_id):

    room = Room.objects.get(pk=room_id)
    # Get all the room messages
    messages = room.room_messages.all().order_by("-updated_at")
    participants = room.participants.all()
    total_participants = participants.count()


    if request.method == 'POST':
        Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get("comment")
        )
        room.participants.add(request.user)
        return redirect("room:room", room.id)

    return render(request, 'room/room.html', {
        "room": room,
        "messages": messages,
        "participants": participants,
        "total_participants": total_participants,
    })


@login_required(login_url="/login")
def userProfile(request, user_id):

    user = User.objects.get(pk=user_id)
    rooms = user.created_rooms.all() # Rooms hosted by the selected user
    topics = Topic.objects.all()
    user_messages = user.user_messages.all()


    return render(request, 'room/profile.html', {
        "user": user,
        "rooms": rooms,
        "room_messages": user_messages,
        "topics": topics,
    })


@login_required(login_url='/login')
def createRoom(request):

    if request.method == 'POST':

        name = request.POST.get("name")
        description = request.POST.get("description")
        topic_name = request.POST.get("topic")

        host = request.user
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(name=name, description=description, host=host, topic=topic)

        return redirect("room:home")


    topics = Topic.objects.all()
    users = User.objects.all()

    return render(request, 'room/create-room.html', {
        "topics": topics,
        "users": users,
    })


@login_required(login_url='room:login')
def update_room(request, room_id):

    selected_room = Room.objects.get(pk=room_id)

    if request.method == 'POST':

        selected_room.name = request.POST.get("name")
        selected_room.description = request.POST.get("description")
        topic_name = request.POST.get("topic")

        topic, created = Topic.objects.get_or_create(name=topic_name)
        selected_room.topic = topic

        selected_room.save()
        return redirect("room:home")


    topics = Topic.objects.all()
    users = User.objects.all()

    return render(request, 'room/update-room.html', {
        "topics": topics,
        "users": users,
        "room": selected_room,
    })


@login_required(login_url='/login')
def delete_room(request, room_id):

    selected_room = Room.objects.get(pk=room_id)

    if request.method == 'POST':
        selected_room.delete()
        return redirect("room:home")

    return render(request, 'room/delete.html', {
        "name": selected_room.name,
    })


@login_required(login_url='/login')
def delete_message(request, room_id, msg_id):

    message = Message.objects.get(pk=msg_id)

    if request.method == 'POST':
        message.delete()
        return redirect("room:room", room_id)

    return render(request, 'room/delete.html', {
        "name": " this message"
    })





def topicsPage(request):

    q = request.GET.get("q") if request.GET.get("q") else ""
    topics = Topic.objects.filter(name__icontains=q)

    room_count = Room.objects.all().count()

    return render(request, 'room/topics.html', {
        "topics": topics,
        "room_count": room_count,
    })


@login_required(login_url="/login")
def editUser(request):
    user = request.user
    form = UserForm(instance=user)


    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect("room:profile", user.id)

    return render(request, 'room/edit-user.html', {
        "user": user,
        "form": form,
    })



def activityPage(request):

    room_messages = Message.objects.all()
    return render(request, 'room/activity.html', {
        "room_messages": room_messages,
    })

django-chat-application/app/room/templates/room/activity.html
{% extends 'room/layout.html' %}


{% block content %}
{% include 'room/components/activity_component.html' %}
{% endblock %}

django-chat-application/app/room/templates/room/create-room.html
{% include 'room/layout.html' %}

{% block content %}
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'room:home' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create Chat Room</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="{% url 'room:create-room' %}" method="post">
            {% csrf_token %}
            <div class="form__group">
              <label for="room_name">Room Name</label>
              <input id="room_name" name="name" type="text" placeholder="E.g. Mastering Python + Django" />
            </div>

            <div class="form__group">
              <label for="room_topic">Topic</label>
              <input required type="text" name="topic" id="room_topic" list="topic-list" />
              <datalist id="topic-list">
                <select id="room_topic">
                  {% for topic in topics %}
                  <option value="{{ topic.name }}">{{ topic.name }}</option>
                  {% endfor %}
                </select>
              </datalist>

            </div>


            <div class="form__group">
              <label for="room_about">About</label>
              <textarea name="description" id="room_about" placeholder="Write about your study group..."></textarea>
            </div>
            <div class="form__action">
              <a class="btn btn--dark" href="{% url 'room:home' %}">Cancel</a>
              <button class="btn btn--main" type="submit">Create Room</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

django-chat-application/app/room/templates/room/edit-user.html
{% extends 'room/layout.html' %}

{% block content %}
    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'room:home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="{% url 'room:edit-user' %}" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% for field in form %}
                        <div class="form__group">
                            <label for="">{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% endfor %}
                        <div class="form__action">
                            <a class="btn btn--dark" href="{% url 'room:home' %}">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>
{% endblock %}

django-chat-application/app/room/templates/room/home.html
{% extends 'room/layout.html' %}

{% block content %}

<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'room/components/topic_component.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    {% include 'room/components/room_component.html' %}
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'room/components/activity_component.html' %}
    <!-- Activities End -->
  </div>
</main>

{% endblock %}

django-chat-application/app/room/templates/room/login.html
{% extends 'room/layout.html' %}

{% load static %}

{% block content %}
  <main class="auth layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <h3>Login</h3>
          </div>
        </div>
        <div class="layout__body">
          <h2 class="auth__tagline">Find your study partner</h2>

          <form class="form" action="{% url 'room:login' %}" method="post">
            {% csrf_token %}
            <div class="form__group form__group">
              <label for="room_name">Email</label>
              <input id="email" name="email" type="text" placeholder="e.g. dennis_ivy@email.com" />
            </div>
            <div class="form__group">
              <label for="password">Password</label>
              <input
                id="password"
                name="password"
                type="password"
                placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
              />
            </div>

            <button class="btn btn--main" type="submit">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 32 32"
              >
                <title>lock</title>
                <path
                  d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                ></path>
                <path
                  d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                ></path>
              </svg>

              Login
            </button>
          </form>

          <div class="auth__action">
            <p>Haven't signed up yet?</p>
            <a href="{% url 'room:register' %}" class="btn btn--link">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

django-chat-application/app/room/templates/room/profile.html
{% extends 'room/layout.html' %}

{% load static %}

{% block content %}
  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include 'room/components/topic_component.html' %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="{{ user.avatar.url }}" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{ user.name }}</h3>
            <p>@{{ user.username }}</p>
            {% if request.user == user %}<a href="{% url 'room:edit-user' %}" class="btn btn--main btn--pill">Edit Profile</a>{% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              {{ user.bio }}
            </p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by {{ user.username }}</a>
            </h2>
          </div>
        </div>
        {% for room in rooms %}
        <div class="roomListRoom">
          <div class="roomListRoom__header">
            <a href="{% url 'room:profile' room.host.id %}" class="roomListRoom__author">
              <div class="avatar avatar--small">
                <img src="{{ room.host.avatar.url }}" />
              </div>
              <span>@{{ room.host.username }}</span>
            </a>
            <div class="roomListRoom__actions">
              <span>{{ room.updated_at | timesince }}</span>
            </div>
          </div>
          <div class="roomListRoom__content">
            <a href="{% url 'room:room' room.id %}">{{ room.name }}</a>
            <p>
                {{ room.description }}
            </p>
          </div>
          <div class="roomListRoom__meta">
            <a href="{% url 'room:room' room.id %}" class="roomListRoom__joined">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                  d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
                ></path>
                <path
                  d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
                ></path>
                <path
                  d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
                ></path>
                <path
                  d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
                ></path>
              </svg>
              5.3k Joined
            </a>
            <p class="roomListRoom__topic">{{ room.topic.name }}</p>
          </div>
        </div>
        {% endfor %}
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      {% include 'room/components/activity_component.html' %}
      <!-- Activities End -->
    </div>
  </main>
{% endblock %}

django-chat-application/app/room/templates/room/register.html
{% extends 'room/layout.html' %}

{% load static %}

{% block content %}
  <main class="auth layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <h3>Login</h3>
          </div>
        </div>
        <div class="layout__body">
          <h2 class="auth__tagline">Find your study partner</h2>

          <form class="form" action="{% url 'room:register' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form__group form__group">
              <label>{{ field.label }}</label>
              {{ field }}
            </div>
            {% endfor %}

            <button class="btn btn--main" type="submit">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 32 32"
              >
                <title>lock</title>
                <path
                  d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                ></path>
                <path
                  d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                ></path>
              </svg>

              Register
            </button>
          </form>

          <div class="auth__action">
            <p>Already have an account?</p>
            <a href="{% url 'room:login' %}" class="btn btn--link">Login</a>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

django-chat-application/app/room/templates/room/room.html
{% extends 'room/layout.html' %}


{% load static %}


{% block content %}
    <main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{% url 'room:home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Study Room</h3>
            </div>
            {% if request.user == room.host %}
            <div class="room__topRight">
              <a href="{% url 'room:update-room' room.id %}">
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>
              <a href="{% url 'room:delete-room' room.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
            {% endif %}


            <!-- <button class="action-button" data-id="120" data-delete-url="https://randomuser.me/api/3324923"
            data-edit-url="profile.html">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>ellipsis-horizontal</title>
              <path
                d="M16 7.843c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 1.98c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
              <path
                d="M16 19.908c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 14.046c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
              <path
                d="M16 31.974c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 26.111c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
            </svg>
          </button> -->
          </div>
          <div class="room__box scroll">
            <div class="room__header scroll">
              <div class="room__info">
                <h3>{{ room.name }}</h3>
                <span style="margin-right: 5px;">{{ room.created_at | timesince }} ago</span>
              </div>
              <div class="room__hosted">
                <p>Hosted By</p>
                <a href="{% url 'room:profile' room.host.id %}" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="{{ room.host.avatar.url }}" />
                  </div>
                  <span>@{{ room.host.username }}</span>
                </a>
              </div>
              <div class="room__details">
                {{ room.description }}
              </div>
              <span class="room__topics">{{ room.topic.name }}</span>
            </div>
            <div class="room__conversation">
              <div class="threads scroll">
                {% for message in messages %}
                <div class="thread">
                  <div class="thread__top">
                    <div class="thread__author">
                      <a href="{% url 'room:profile' message.user.id %}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
                          <img src="{{ message.user.avatar.url }}" />
                        </div>
                        <span>@{{ message.user.username }}</span>
                      </a>
                      <span class="thread__date">{{ message.updated_at | timesince }}</span>
                    </div>
                    {% if request.user == message.user %}
                    <a href="{% url 'room:delete-message' room.id message.id %}">
                      <div class="thread__delete">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                          <title>remove</title>
                          <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                          ></path>
                        </svg>
                      </div>
                    </a>
                    {% endif %}
                  </div>
                  <div class="thread__details">
                    {{ message.body }}
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="room__message">
            <form action="{% url 'room:room' room.id %}" method="post">
              {% csrf_token %}
              <input name="comment" placeholder="Write your message here..." />
            </form>
          </div>
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          <h3 class="participants__top">Participants <span>{{ total_participants }} joined.</span></h3>
          <div class="participants__list scroll">
            {% for participant in participants %}
            <a href="{% url 'room:profile' participant.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="{{ participant.avatar.url }}" />
              </div>
              <p>
                {{ participant.username }}
                <span>@{{ participant.username }}</span>
              </p>
            </a>
            {% endfor %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
{% endblock %}