django-chat-application/app/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("room.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


django-chat-application/app/room/urls.py
from django.urls import path

from . import views


app_name = "room"

urlpatterns = [
    path("", views.home_page, name="home"),


    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('register/', views.register_user, name='register'),


    path("room/", views.rooms_page, name="rooms"),
    path("room/<int:room_id>", views.get_room, name="room"),
    path("room/create/", views.createRoom, name="create-room"),
    path("room/edit/<int:room_id>", views.update_room, name="update-room"),
    path('room/delete/<int:room_id>', views.delete_room, name="delete-room"),
    path('room/<int:room_id>/delete-message/<int:msg_id>/', views.delete_message, name='delete-message'),


    path('topics/', views.topicsPage, name='topics'),
    path('activity/', views.activityPage, name='activity'),


    path("profile/<int:user_id>/", views.userProfile, name="profile"),
    path("edit-profile/", views.editUser, name="edit-user"),
]

django-chat-application/app/room/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):

    name = models.CharField(max_length=64)
    email = models.EmailField(unique=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True, default='avatar.svg')


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name
    

class Room(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="created_rooms")
    participants = models.ManyToManyField(User, related_name="participants", blank=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True, related_name="rooms")


    class Meta:
        ordering = ['-updated_at', '-created_at']


    def __str__(self):
        return self.name



class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_messages")
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="room_messages")
    body = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']


    def __str__(self):
        return self.body[0:50]

django-chat-application/app/room/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

django-chat-application/app/room/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import MyUserCreationForm

from room.forms import UserForm

from django.shortcuts import render, redirect
from django.db.models import Q


from room.models import *


# Create your views here.


def register_user(request):

    form_template = MyUserCreationForm()

    if request.method == 'POST':

        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect("room:home")
        else:
            return render(request, 'room/login.html', {
                "message": "an error occured during registration. Please try again",
                "form": form_template,
            })

    return render(request, 'room/register.html', {
        "form": form_template,
    })


def login_page(request):

    if request.method == 'POST':

        if request.user.is_authenticated:
            return redirect("room:home")
        
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = None
        try:
            user = User.objects.get(email=email)
        except:
            return render(request, 'room/login.html', {
                "message": "Email does not exist"
            })
        else:
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect("room:home")
            return render(request, 'room/login.html', {
                "message": "Invalid login credentials"
            })

    # if there is a get request        
    return render(request, 'room/login.html')


def logout_page(request):

    if request.user.is_authenticated:
        logout(request)
    
    return redirect("room:login")


def home_page(request):

    q = request.GET.get("q") if request.GET.get("q") else ""

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )
    topics = Topic.objects.all()[0:5]
    room_messages = Message.objects.filter(
        Q(room__name__icontains=q) |
        Q(room__topic__name__icontains=q)
    )

    room_count = rooms.count()

    return render(request, 'room/home.html', {
        "rooms": rooms,
        "topics": topics,
        "room_count": room_count,
        "room_messages": room_messages,
    })



def rooms_page(request):

    # Query all the available rooms
    available_rooms = Room.objects.all()

    return render(request, "room/rooms.html", {
        "rooms": available_rooms
    })


def get_room(request, room_id):

    room = Room.objects.get(pk=room_id)
    # Get all the room messages
    messages = room.room_messages.all().order_by("-updated_at")
    participants = room.participants.all()
    total_participants = participants.count()


    if request.method == 'POST':
        Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get("comment")
        )
        room.participants.add(request.user)
        return redirect("room:room", room.id)

    return render(request, 'room/room.html', {
        "room": room,
        "messages": messages,
        "participants": participants,
        "total_participants": total_participants,
    })


@login_required(login_url="/login")
def userProfile(request, user_id):

    user = User.objects.get(pk=user_id)
    rooms = user.created_rooms.all() # Rooms hosted by the selected user
    topics = Topic.objects.all()
    user_messages = user.user_messages.all()


    return render(request, 'room/profile.html', {
        "user": user,
        "rooms": rooms,
        "room_messages": user_messages,
        "topics": topics,
    })


@login_required(login_url='/login')
def createRoom(request):

    if request.method == 'POST':

        name = request.POST.get("name")
        description = request.POST.get("description")
        topic_name = request.POST.get("topic")

        host = request.user
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(name=name, description=description, host=host, topic=topic)

        return redirect("room:home")


    topics = Topic.objects.all()
    users = User.objects.all()

    return render(request, 'room/create-room.html', {
        "topics": topics,
        "users": users,
    })


@login_required(login_url='room:login')
def update_room(request, room_id):

    selected_room = Room.objects.get(pk=room_id)

    if request.method == 'POST':

        selected_room.name = request.POST.get("name")
        selected_room.description = request.POST.get("description")
        topic_name = request.POST.get("topic")

        topic, created = Topic.objects.get_or_create(name=topic_name)
        selected_room.topic = topic

        selected_room.save()
        return redirect("room:home")


    topics = Topic.objects.all()
    users = User.objects.all()

    return render(request, 'room/update-room.html', {
        "topics": topics,
        "users": users,
        "room": selected_room,
    })


@login_required(login_url='/login')
def delete_room(request, room_id):

    selected_room = Room.objects.get(pk=room_id)

    if request.method == 'POST':
        selected_room.delete()
        return redirect("room:home")

    return render(request, 'room/delete.html', {
        "name": selected_room.name,
    })


@login_required(login_url='/login')
def delete_message(request, room_id, msg_id):

    message = Message.objects.get(pk=msg_id)

    if request.method == 'POST':
        message.delete()
        return redirect("room:room", room_id)

    return render(request, 'room/delete.html', {
        "name": " this message"
    })





def topicsPage(request):

    q = request.GET.get("q") if request.GET.get("q") else ""
    topics = Topic.objects.filter(name__icontains=q)

    room_count = Room.objects.all().count()

    return render(request, 'room/topics.html', {
        "topics": topics,
        "room_count": room_count,
    })


@login_required(login_url="/login")
def editUser(request):
    user = request.user
    form = UserForm(instance=user)


    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect("room:profile", user.id)

    return render(request, 'room/edit-user.html', {
        "user": user,
        "form": form,
    })



def activityPage(request):

    room_messages = Message.objects.all()
    return render(request, 'room/activity.html', {
        "room_messages": room_messages,
    })

django-chat-application/app/room/templates/room/components/activity_component.html
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
        <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'room:profile' message.user.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{ message.user.avatar.url }}" />
            </div>
            <p>
                @{{ message.user.username }}
                <span>{{ message.updated_at | timesince }} ago.</span>
            </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
            <a href="{% url 'room:delete-message' message.room.id message.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                ></path>
                </svg>
            </a>
            </div>
            {% endif %}
        </div>
        <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'room:room' message.room.id %}">{{ message.room.name }}</a>”</p>
            <div class="activities__boxRoomContent">
            {{ message.body }}
            </div>
        </div>
        </div>
    {% endfor %}
  </div>

django-chat-application/app/room/templates/room/components/navbar_component.html
{% load static %}

<header class="header header--loggedIn">
    <div class="container">
      <a href="{% url 'room:home' %}" class="header__logo">
        <img src="{% static 'assets/logo.svg' %}" />
        <h1>Chat.it</h1>
      </a>
      <form class="header__search" action="{% url 'room:home' %}" method="post">
        {% csrf_token %}
        <label>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>search</title>
            <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
            ></path>
          </svg>
          <input placeholder="Search for rooms..." name="q"/>
        </label>
      </form>
      <nav class="header__menu">
        <!-- Not Logged In -->
        {% if not request.user.is_authenticated %}
            <a href="{% url 'room:login' %}">
            <img src="{% static 'images/avatar.svg' %}" />
            <p>Login</p>
            </a>
        {% else %}

        <!-- Logged In -->

        <div class="header__user">
          <a href="{% url 'room:profile' request.user.id %}">
            <div class="avatar avatar--medium active">
              <img src="{{request.user.avatar.url}}" />
            </div>
            <p>{{ request.user.name }}<span>@{{ request.user.username }}</span></p>
          </a>
          <button class="dropdown-button">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>chevron-down</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </button>
        </div>

        <div class="dropdown-menu">
          <a href="{% url 'room:edit-user' %}" class="dropdown-link"
            ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>tools</title>
              <path
                d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
              ></path>
            </svg>
            Settings</a
          >
          <a href="{% url 'room:logout' %}" class="dropdown-link"
            ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>sign-out</title>
              <path
                d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
              ></path>
              <path
                d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
              ></path>
            </svg>
            Logout</a
          >
        </div>
      </nav>
      {% endif %}
    </div>
  </header>

django-chat-application/app/room/templates/room/components/room_component.html
<div class="roomList">
    <div class="mobile-menu">
      <form class="header__search" action="{% url 'room:home' %}" method="get">
        <label>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>search</title>
            <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
            ></path>
          </svg>
          <input placeholder="Search for posts" name="q"/>
        </label>
      </form>
      <div class="mobile-menuItems">
        <a class="btn btn--main btn--pill" href="{% url 'room:topics' %}">Browse Topics</a>
        <a class="btn btn--main btn--pill" href="{% url 'room:activity' %}">Recent Activities</a>
      </div>
    </div>
    <div class="roomList__header">
      <div>
        <h2>Chat room</h2>
        <p>{{ room_count }} rooms available</p>
      </div>
      <a class="btn btn--main" href="{% url 'room:create-room' %}">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>add</title>
          <path
            d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
          ></path>
        </svg>
        Create Room
      </a>
    </div>
    {% for room in rooms %}
    <div class="roomListRoom">
      <div class="roomListRoom__header">
        <a href="{% url 'room:profile' room.host.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="{{ room.host.avatar.url }}" />
          </div>
          <span>@{{ room.host.username }}</span>
        </a>
        <div class="roomListRoom__actions">
          <span>{{ room.updated_at | timesince }} ago.</span>
        </div>
      </div>
      <div class="roomListRoom__content">
        <a href="{% url 'room:room' room.id %}">{{ room.name }}</a>
        <p>
            {{ room.description }}
        </p>
      </div>
      <div class="roomListRoom__meta">
        <a href="{% url 'room:room' room.id %}" class="roomListRoom__joined">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>user-group</title>
            <path
              d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
            ></path>
            <path
              d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
            ></path>
            <path
              d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
            ></path>
            <path
              d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
            ></path>
          </svg>
          {{ room.participants.all.count}} joined
        </a>
        <p class="roomListRoom__topic">{{ room.topic.name }}</p>
      </div>
    </div>
    {% endfor %}
  </div>

django-chat-application/app/room/templates/room/components/topic_component.html
<div class="topics">
    <div class="topics__header">
      <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="/" class="active">All <span>{{ rooms.all.count }}</span></a>
      </li>
        {% for topic in topics %}
        <li>
          <a href="{% url 'room:home' %}?q={{topic.name}}">{{topic.name}} <span>{{ topic.rooms.all.count }}</span></a>
        </li>
        {% endfor %}
    </ul>
    <a class="btn btn--link" href="{% url 'room:topics' %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>


  <!--Edit the topics.html page and corresponding route in line 12-->